version: "3.9"
services:
  postgres:
    container_name: pfdb
    image: postgres:latest
    environment: 
      POSTGRES_DB: "PolyFloraDB"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "1111"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  redis:
    container_name: pfredis
    image: redis:latest
    ports:
      - "6379:6379"
    depends_on:
      - postgres

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge